# These are supported funding model platforms

github:  [kavindyasinthasilva]
patreon: kavindyasinthasilva
open_collective: kavindyasinthasilva
ko_fi: kavindyasinthasilva
tidelift: kavindyasinthasilva
community_bridge: skysoftlk
liberapay: kavindyasinthasilva
issuehunt: kavindyasinthasilva
otechie: kavindyasinthasilva
custom:  ['https://kavinduyasintha.blogspot.com/']
